### ISSUE TITLE
Update FR localizations

### ISSUE THREAD

**Issue by Bari77** [flexmonster/pivot-localizations#1]
Hey,

is it possible to update https://github.com/flexmonster/pivot-localizations/blob/master/fr.json and build it on https://raw.githubusercontent.com/flexmonster/pivot-localizations/master/fr.json with this trads :
```
"fieldsList": {
    "allFields": "Tout les chammps",
    "dropField": "Glissez déposez ici",
    "subtitle": "Glissez déposez les champs pour organiser"
}
```
please :)

Cordialy, Bari.

**Comment by flexmonster** [comment]
Hi Bari,

Thank you for your request. 
Please check the updated version.

**Comment by Bari77** [comment]
Hi,

Thank to change it, but i do a misstake : 
`"allFields": "Tout les champs",` => one "m". Sorry to saw that later.

Cordialy, Bari.

**Comment by Bari77** [comment]
Thank a lot for french user, we can close this issue.

**Comment by flexmonster** [comment]
Hi, Sebastien,
Thank you for your contribution! 
The French localization is updated now.
